### ISSUE TITLE
[nyaa.si] Category Icons

### ISSUE THREAD

**Issue by cybern4ut** [jesuscc1993/user-css#3]
Hi! First off it's not really an issue but more of a request and wondering if it's something you'll be working on or nah. I remember when you had different icons for the categories on nyaa. Love the big searchbar and all you did but was wondering if it's something you'll do in the future.

Much obliged and sorry to post this here I just didn't know where to post that request.

**Comment by jesuscc1993** [comment]
This is the place to ask, don't worry.
About your request I lost those images long ago and I had to remove the option.
To add the option back I would have to create them again from scratch, which is why I haven't.
I may look into this once more, since you reuqested it, but I won't make any promises.

**Comment by jesuscc1993** [comment]
The setting is back; I added images for all categories except for live action.

**Comment by cybern4ut** [comment]
> The setting is back; I added images for all categories except for live action.

Super nice, I love them!
